apiVersion: apps/v1
kind: Deployment
metadata:
  name: insurance-deployment
  labels:
    app: insurance
spec:
  replicas: 2
  selector:
    matchLabels:
      app: insurance
  template:
    metadata:
      labels:
        app: insurance
    spec:
      containers:
      - name: insurance
        image: nikithamanvi/insurance:latest
        ports:
        - containerPort: 8083
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: insurance-service
spec:
  selector:
    app: insurance
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8083
  type: NodePort
