apiVersion: v1
kind: Service
metadata:
  name: insurance-service
spec:
  type: NodePort
  selector:
    app: insurance
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8083
      nodePort: 31369
