apiVersion: v1
kind: Service
metadata:
  name: insurance-service
spec:
  type: LoadBalancer
  selector:
    app: insurance
  ports:
    - name: http
      protocol: TCP
      port: 80          # Port exposed to outside world
      targetPort: 8083  # Port inside the container
      nodePort: 31369
